table Table
	lineageTag: f520bb5f-7c94-4281-99be-0234bbe915e2

	column Column1
		dataType: string
		lineageTag: b0c3aa3d-af46-4fd8-98fe-d83958388626
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: int64
		formatString: 0
		lineageTag: 24635a6d-b56d-4a66-920a-cd2bbf60f230
		summarizeBy: sum
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition Table = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WylDSUbJQio0FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t]),
				  #"Changed column type" = Table.TransformColumnTypes(Source, {{"Column1", type text}, {"Column2", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

